"""init

Revision ID: c79e1785119e
Revises: 
Create Date: 2022-01-18 17:21:21.493668

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c79e1785119e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.add_column('article', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_article_create_time'), 'article', ['create_time'], unique=False)
    op.create_index(op.f('ix_article_img'), 'article', ['img'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_img'), table_name='article')
    op.drop_index(op.f('ix_article_create_time'), table_name='article')
    op.drop_column('article', 'create_time')
    op.drop_column('article', 'img')
    # ### end Alembic commands ###
